spring:
  cloud.stream:
    kafka.streams:
      binder:
        serde-error: logandcontinue
        brokers: "kafka:9092"
        configuration:
          commit.interval.ms: 1000
          default:
            key.serde: com.salmon.schemas.serde.UUIDSerde
      bindings:
        users-in:
          consumer:
            materialized-as: users-mv
            value-serde: com.salmon.schemas.serde.JsonSerde$UserDataSerde
        follows-in:
          consumer:
            materialized-as: follows-mv
            value-serde: com.salmon.schemas.serde.JsonSerde$UserFollowsSerde
        tweets-in.consumer.value-serde: com.salmon.schemas.serde.JsonSerde$TweetSerde
    bindings:
      users-in:
        destination: Users
        group: user-tweets
        content-type: application/json
        consumer:
          header-mode: raw
          use-native-decoding: true
      follows-in:
        destination: UserFollows
        group: user-tweets
        content-type: application/json
        consumer:
          header-mode: raw
          use-native-decoding: true
      tweets-in:
        destination: Tweets
        group: user-tweets
        content-type: application/json
        consumer:
          header-mode: raw
          use-native-decoding: true
  kafka:
    bootstrap-servers: "kafka:9092"
    producer:
      bootstrap-servers: "kafka:9092"
    consumer:
      bootstrap-servers: "kafka:9092"
  jackson.serialization.INDENT_OUTPUT: true

server:
  port: 13003

debug: true
