spring:
  cloud.stream:
    kafka.streams:
      binder:
        serde-error: logandcontinue
        brokers: "kafka:9092"
        configuration:
          commit.interval.ms: 1000
          default:
            key.serde: com.salmon.schemas.serde.UUIDSerde
    bindings:
      users-out:
        destination: Users
        content-type: application/json
        producer:
          header-mode: raw
          use-native-encoding: false
      tweets-out:
        destination: Tweets
        content-type: application/json
        producer:
          header-mode: raw
          use-native-encoding: false
  kafka:
    bootstrap-servers: "kafka:9092"
    producer:
      bootstrap-servers: "kafka:9092"
    consumer:
      bootstrap-servers: "kafka:9092"

server:
  port: 11003

debug: true
