version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Users:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: wurstmeister/kafka
    links:
      - zookeeper
  event-producer:
    build: components/event-producer
    links:
      - kafka
    ports:
      - "11003:11003"
    depends_on:
      - kafka
  tweet-enricher:
    build: components/tweet-enricher
    links:
      - kafka
      - zookeeper
    ports:
      - "12003:12003"
    depends_on:
      - kafka
      - zookeeper
  user-tweets:
    build: components/user-tweets
    links:
      - kafka
      - zookeeper
    ports:
      - "13003:13003"
    depends_on:
      - kafka
      - zookeeper