spring:
  cloud.stream:
    kafka.streams:
      binder:
        serde-error: logandcontinue
        brokers: "kafka:9092"
        configuration:
          commit.interval.ms: 1000
          default:
            key.serde: com.salmon.schemas.serde.UUIDSerde
      bindings:
        users-in:
          consumer:
            materialized-as: users-mv
            value-serde: com.salmon.schemas.serde.JsonSerde$UserDataSerde
        tweets-in.consumer.value-serde: com.salmon.schemas.serde.JsonSerde$TweetSerde
        enriched-tweets-out.producer.value-serde: com.salmon.schemas.serde.JsonSerde$EnrichedTweetSerde
    bindings:
      users-in:
        destination: Users
        group: user-enricher
        content-type: application/json
        consumer:
          header-mode: raw
          use-native-decoding: true
      tweets-in:
        destination: Tweets
        group: user-enrincher
        content-type: application/json
        consumer:
          header-mode: raw
          use-native-decoding: true
      enriched-tweets-out:
        destination: EnrichedTweets
        content-type: application/json
        produced:
          header-mode: raw
          use-native-encoding: true
  kafka:
    bootstrap-servers: "kafka:9092"
    producer:
      bootstrap-servers: "kafka:9092"
    consumer:
      bootstrap-servers: "kafka:9092"

server:
  port: 12003

debug: true
