spring:
  cloud.stream:
    kafka.streams:
      binder:
        brokers: "kafka:9092"
        configuration:
          commit.interval.ms: 1000
          default:
            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    bindings:
      users:
        destination: UsersById
        group: user-enricher
        content-type: application/json
        consumer.header-mode: raw
      pageviewsin:
        destination: PageViewEvent
        group: user-enrincher
        content-type: application/json
        consumer.header-mode: raw
      enrichedpageviewsout:
        destination: EnrichedPageViewEvent
        produced.header-mode: raw
  kafka:
    bootstrap-servers: "kafka:9092"
    producer:
      bootstrap-servers: "kafka:9092"
    consumer:
      bootstrap-servers: "kafka:9092"

server:
  port: 12003

debug: true
