spring:
  cloud.stream:
    kafka.streams:
      binder:
        brokers: "kafka:9092"
        configuration:
          commit.interval.ms: 1000
          default:
            key.serde: com.salmon.schemas.serde.UUIDSerde
            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    bindings:
      users-in:
        destination: UsersById
        group: user-enricher
        content-type: application/json
        consumer:
          header-mode: raw
          use-native-decoding: true
      tweets-in:
        destination: Tweets
        group: user-enrincher
        content-type: application/json
        consumer:
          header-mode: raw
          use-native-decoding: true
      enriched-tweets-out:
        destination: EnrichedTweet
        content-type: application/json
        produced:
          header-mode: raw
          use-native-encoding: true
  kafka:
    bootstrap-servers: "kafka:9092"
    producer:
      bootstrap-servers: "kafka:9092"
    consumer:
      bootstrap-servers: "kafka:9092"

server:
  port: 12003

debug: true
